cursor #1d1a24
cursor_text_color #494551

foreground            #1d1a24
background            #fdf7ff
selection_foreground  #ffffff
selection_background  #d6bee5
url_color             #6a1eff

color0   #14121c
color1   #f20030
color2   #00bf29
color3   #ffbc00
color4   #6212ff
color5   #cfb7ff
color6   #6a1eff
color7   #444247
color8   #d2cfd8
color9   #ff1e4a
color10  #07ff3c
color11  #ffbc00
color12  #8a3cff
color13  #cfb7ff
color14  #b48eff
color15  #f9f6ff
